keys:
  - &admin age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy
  # maintainers
  - &larsg age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy

creation_rules:
  # Project management secrets
  - path_regex: project/secrets/[^/]+\.(yaml|json)$
    key_groups:
      - age:
          - *admin
          - *larsg
